name: shared-latent-space
channels:
  - defaults
dependencies:
  - absl-py=0.2.1=py27_0
  - astor=0.6.2=py27_0
  - backports=1.0=py27h63c9359_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.weakref=1.0.post1=py27h0df1112_0
  - backports_abc=0.5=py27h7b3c97b_0
  - blas=1.0=mkl
  - bleach=1.5.0=py27_0
  - bokeh=0.12.16=py27_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py27_0
  - click=6.7=py27h4225b90_0
  - cloudpickle=0.5.3=py27_0
  - cycler=0.10.0=py27hc7354d3_0
  - cytoolz=0.9.0.1=py27h14c3975_0
  - dask=0.17.5=py27_0
  - dask-core=0.17.5=py27_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py27_0
  - distributed=1.21.8=py27_0
  - enum34=1.1.6=py27h99a27e9_1
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - funcsigs=1.0.2=py27h83f16ab_0
  - functools32=3.2.3.2=py27h4ead58f_1
  - futures=3.2.0=py27h7b459c0_0
  - gast=0.2.0=py27_0
  - glib=2.56.1=h000015b_0
  - grpcio=1.11.0=py27hf484d3e_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.7.1=py27h2697762_0
  - hdf5=1.10.1=h9caa474_1
  - heapdict=1.0.0=py27_2
  - html5lib=0.9999999=py27_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.3.0=py27_0
  - intel-openmp=2018.0.0=8
  - jinja2=2.10=py27h4114e70_0
  - jpeg=9b=h024ee3a_2
  - keras=2.1.5=py27_0
  - kiwisolver=1.0.1=py27hc15e7b5_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he85c1e1_1
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=hf84eae3_0
  - locket=0.2.0=py27h73929a2_1
  - markdown=2.6.11=py27_0
  - markupsafe=1.0=py27h97b2822_1
  - matplotlib=2.2.2=py27h0e671d2_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py27h3010b51_0
  - mkl_random=1.0.1=py27h629b387_0
  - mock=2.0.0=py27h0c0c831_0
  - msgpack-python=0.5.6=py27h6bb024c_0
  - ncurses=6.1=hf484d3e_0
  - networkx=2.1=py27_0
  - numpy=1.14.3=py27hcd700cb_1
  - numpy-base=1.14.3=py27h9be14a7_1
  - olefile=0.45.1=py27_0
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py27_0
  - pandas=0.23.0=py27h637b7d7_0
  - partd=0.3.8=py27h4e55004_0
  - patsy=0.5.0=py27_0
  - pbr=4.0.3=py27_0
  - pcre=8.42=h439df22_0
  - pillow=5.1.0=py27h3deb7b8_0
  - pip=10.0.1=py27_0
  - protobuf=3.5.2=py27hf484d3e_0
  - psutil=5.4.5=py27h14c3975_0
  - pyparsing=2.2.0=py27hf1513f8_1
  - pyqt=5.9.2=py27h751905a_0
  - python=2.7.14=h1571d57_31
  - python-dateutil=2.7.3=py27_0
  - pytz=2018.4=py27_0
  - pywavelets=0.5.2=py27hecda097_0
  - pyyaml=3.12=py27h2d70dd7_1
  - qt=5.9.5=h7e424d6_0
  - readline=7.0=ha6073c6_4
  - scikit-image=0.13.1=py27h14c3975_1
  - scipy=1.0.0=py27hf5f0f52_0
  - seaborn=0.8.1=py27h633ea1e_0
  - setuptools=39.1.0=py27_0
  - singledispatch=3.4.0.3=py27h9bcb476_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.11.0=py27h5f960f1_1
  - sortedcontainers=1.5.10=py27_0
  - sqlite=3.23.1=he433501_0
  - statsmodels=0.9.0=py27h3010b51_0
  - subprocess32=3.5.0=py27h14c3975_0
  - tblib=1.3.2=py27h51fe5ba_0
  - tensorboard=1.7.0=py27hf484d3e_1
  - tensorflow=1.7.0=0
  - tensorflow-base=1.7.0=py27hdbcaa40_2
  - termcolor=1.1.0=py27_1
  - tk=8.6.7=hc745277_3
  - toolz=0.9.0=py27_0
  - tornado=5.0.2=py27_0
  - werkzeug=0.14.1=py27_0
  - wheel=0.31.1=py27_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zict=0.1.3=py27h12c336c_0
  - zlib=1.2.11=ha838bed_2
  - pydot=1.2.4
prefix: /home/chriswilliams/anaconda2/envs/shared-latent-space

